import fs from 'node:fs';
const config=JSON.parse(fs.readFileSync('config.json','utf8'));
const read=name=>JSON.parse(fs.readFileSync('data/'+name+'.json','utf8'));
const records=read('records'),schools=read('schools'),release_notes=read('release-notes');
const programs=read('programs'),coverage=read('coverage'),scope=read('scope');
const targetIds=new Set([...scope.ranking.rows,...scope.asia].map(p=>p.program_id));
for(const r of records)r.target_scope=targetIds.has(r.program_id)?scope.id:null;
for(const p of programs)p.record_count=records.filter(r=>r.program_id===p.id).length;
const catalog={...config,exhaustive:false,scope,programs,coverage,archive_years:[...new Set([...config.history_years,...records.map(r=>r.placement_year).filter(Boolean)])].sort(),schools,release_notes};
fs.mkdirSync('dist/data',{recursive:true});
fs.writeFileSync('dist/data/records.json',JSON.stringify(records,null,2)+'\n');
fs.writeFileSync('dist/data/catalog.json',JSON.stringify(catalog,null,2)+'\n');
fs.writeFileSync('dist/data/scope.json',JSON.stringify(scope,null,2)+'\n');
console.log(`Synchronized ${records.length} people; current cycle ${catalog.current_cycle}; ${catalog.history_years.length} historical years.`);
